[package]
name = "rsdl2"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Simple DirectMedia Layer"
license = "Zlib"

[dependencies]
bitflags = "1.0"
libc = { version = "0.2", default-features = false }
null-terminated = "0.2.7"
ptr = "0.1"
sdl2-sys = "0.31"
