[package]
name = "rsdl2-sys"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "SDL2 low-level bonds"
license = "Zlib"

[lib]
name = "sdl2_sys"

[dependencies]
libc = { version = "0.2", default-features = false }

[build-dependencies]
bindgen = "0.56"
